name: CI

on:
  workflow_dispatch:
  


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: ghcr.io
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
    
    - run: |
        docker build -t ghcr.io/JCARLOS3009/postgre-docker:latest -f Dockerfile .
        docker tag ghcr.io/JCARLOS3009/postgre-docker:latest ghcr.io/JCARLOS3009/postgre-docker:${{ github.sha }}
    
    - run: |
        docker push ghcr.io/JCARLOS3009/postgre-docker:latest
        docker push ghcr.io/JCARLOS3009/postgre-docker:${{ github.sha }}
